- name: Setup new server
  hosts: ninth
  tasks:
    - name: Install important packages
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true
      become: true

    - name: Install /etc/apt/keyrings
      ansible.builtin.shell:
        cmd: install -m 0755 -d /etc/apt/keyrings
      become: true

    - name: Install Docker GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo --dearmor -o /etc/apt/keyrings/docker.gpg && sudo chmod a+r /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg
      become: true

    - name: Add Docker source
      ansible.builtin.shell:
        cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list
      become: true

    - name: Install Docker packages
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
      become: true

    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
      become: true

    - name: Add user mpfl to docker
      ansible.builtin.user:
        append: true
        groups: docker
        name: mpfl
      become: true
      register: group_added

    - name: If needed, restart docker engine
      ansible.builtin.service:
        name: containerd
        state: restarted
      when: group_added == changed

